name: Terraform CI

on:
  push:
    branches:
      - main
  
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check Terraform version
        run: terraform --version
      
      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate